import { CategoryItem } from "@/context/AdminContext";

export const getDefaultCategories = (): CategoryItem[] => [
  {
    id: "cat-1",
    name: "CPAP Therapy",
    slug: "sleep-apnea-therapy",
    image: "/images/pulmocare/pulmocare_prisma-smart-plus.png",
    count: "3 Models",
    badge: "Most Popular",
    desc: "Premium auto-CPAP titration for obstructive sleep apnea.",
  },
  {
    id: "cat-2",
    name: "Bilevel-S & ST Devices",
    slug: "bilevel-s-st-devices",
    image: "/images/pulmocare/pulmocare_prisma-25-st.png",
    count: "3 Models",
    badge: "Clinical Grade",
    desc: "High pressure support BiLevel S and ST therapy.",
  },
  {
    id: "cat-3",
    name: "ASV & Titration Devices",
    slug: "asv-titration-devices",
    image: "/images/pulmocare/pulmocare_prisma-lab.png",
    count: "2 Models",
    badge: "Advanced Tech",
    desc: "Adaptive servo-ventilation and lab titration.",
  },
  {
    id: "cat-4",
    name: "Humidifiers",
    slug: "humidifiers",
    image: "/images/pulmocare/pulmocare_prisma-aqua.png",
    count: "2 Models",
    desc: "Heated humidification for patient comfort.",
  },
  {
    id: "cat-5",
    name: "Ventilation",
    slug: "ventilation",
    image: "/images/pulmocare/pulmocare_luisa-ventilator.png",
    count: "3 Models",
    badge: "Life Support",
    desc: "Hospital & home care life support ventilators.",
  },
  {
    id: "cat-6",
    name: "Oxygen Therapy",
    slug: "oxygen-therapy",
    image: "/images/pulmocare/pulmocare_inogen-rove-6.png",
    count: "2 Models",
    badge: "High Purity",
    desc: "Portable & stationary 5L LPM oxygen concentrators.",
  },
  {
    id: "cat-7",
    name: "Sleep Diagnostics",
    slug: "sleep-diagnostics",
    image: "/images/site/sleep_diagnostics_csm_samoa_sleep_diagnostics_device_frontal_dba1194f3b.png",
    count: "3 Models",
    desc: "10-33 channel polygraphy and polysomnography.",
  },
  {
    id: "cat-8",
    name: "Masks",
    slug: "masks",
    image: "/images/pulmocare/pulmo_l-wenstein-lena.png",
    count: "5 Models",
    badge: "Ergonomic Seal",
    desc: "Nasal and full face ventilation patient masks.",
  },
];
